---
- name: Add hypervisor
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Add the hypervisor to the in-memory inventory
      add_host:
        name: hypervisor
        ansible_host: "{{ molecule_yml.driver.options.host }}"
        ansible_port: "{{ molecule_yml.driver.options.port | default(omit) }}"
        ansible_connection: "{{ molecule_yml.driver.options.connection | default(omit) }}"
        ansible_python_interpreter: "{{ molecule_yml.driver.options.python_interpreter | default(omit) }}"
      changed_when: false

- name: Create
  hosts: hypervisor
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Create molecule instance(s)
      virt_up:
        state: up
        name: "{{ item.name }}"
        template: "{{ item.template }}"
        size: "{{ item.size | default(omit) }}"
        memory: "{{ item.memory | default(omit) }}"
        cpus: "{{ item.cpus | default(omit) }}"
        sshdir: "{{ molecule_ephemeral_directory }}"
        logfile: "{{ molecule_yml.driver.options.logfile | default(omit) }}"
        loglevel: "{{ molecule_yml.driver.options.loglevel | default(omit) }}"
      loop: "{{ molecule_yml.platforms }}"
      register: virt_up

    - name: Fetch ssh identity files.
      when: virt_up.changed
      block:
        - name: Fetch private key files.
          fetch:
            flat: yes
            src: "{{ item.remote_identity_file }}"
            dest: "{{ item.server.identity_file }}"
          loop: "{{ virt_up.results }}"

        - name: Fetch public key files.
          fetch:
            flat: yes
            src: "{{ item.remote_identity_file }}.pub"
            dest: "{{ item.server.identity_file }}.pub"
          loop: "{{ virt_up.results }}"

        - name: Set private key file permissions.
          local_action:
            module: file
            state: file
            mode: "0600"
            path: "{{ item.server.identity_file }}"
          loop: "{{ virt_up.results }}"

        - name: Set public key file permissions.
          local_action:
            module: file
            state: file
            mode: "0644"
            path: "{{ item.server.identity_file }}.pub"
          loop: "{{ virt_up.results }}"

    - name: Convert results to instance config.
      when: virt_up.changed
      set_fact:
        instance_conf: "{{ virt_up.results | map(attribute='server') | list }}"

    - name: Write instance config
      when: virt_up.changed
      local_action:
        module: copy
        content: "{{ instance_conf }}"
        dest: "{{ molecule_instance_config }}"
