---
- name: Wait for instances
  hosts: all
  gather_facts: no
  tasks:
    - name: Waiting for system to start
      wait_for_connection:

- name: Prepare
  hosts: all
  tasks:
    - name: Set hostname address mapping
      become: yes
      copy:
        backup: yes
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          {{ ansible_default_ipv4.address }} {{ ansible_hostname}}
